import { test, expect, type Page } from '@playwright/test';
import { IGNORABLE_ERROR_PATTERNS } from './routes';

// Ticket 0043 - Emit ItemList JSON-LD on /changelog so search engines can
// index individual ship entries. Each test maps 1:1 to an acceptance-criteria
// box on the ticket. Modeled on tests/e2e/quiz-jsonld.spec.ts (ticket 0039,
// the closest peer for "publish structure of an existing artifact").
//
// /changelog already renders a list of shipped backlog tickets sourced from
// src/data/changelogEntries.ts (regenerated by scripts/generate-changelog.ts
// at build time). This ticket inlines two sibling
// <script type="application/ld+json"> tags into the existing Helmet head:
// an ItemList block whose itemListElement is mapped from the SAME sliced
// render array (the VISIBLE_LIMIT=36 cap), and a BreadcrumbList block
// (Home -> Changelog) matching the pattern in src/pages/AiForElectricians.tsx
// and src/pages/compare/Podium.tsx.
//
// Per the 2026-05-25 SEO Pilot lesson the spec does NOT use
// page.toHaveTitle() because /changelog is not in the index.html SEO Pilot
// pages table (a fact already documented at src/pages/Changelog.tsx lines
// 19-24). The spec reads the LAST meta[name="description"] (the
// Helmet-appended one) and asserts it byte-for-byte equals the ItemList
// block's description (the mirror-source guarantee from the 2026-05-25
// lesson). Per the 2026-05-30 second-@type lesson, the implementer grepped
// every existing tests/e2e/*-jsonld.spec.ts for `=== 'ItemList'` and
// `=== 'BreadcrumbList'` before writing code and confirmed every "exactly
// one" predicate is URL-scoped (to /demos or / today), so adding new
// /changelog-scoped blocks is safe.

const isIgnorable = (msg: string) =>
  IGNORABLE_ERROR_PATTERNS.some((re) => re.test(msg));

// U+2014 spelled via fromCharCode so this file itself contains no em-dash
// (the brand-voice Hard NO bans the literal character even in tests).
const EM_DASH = String.fromCharCode(8212);

const ORIGIN = 'https://digitalcraftai.com';
const CHANGELOG_URL = `${ORIGIN}/changelog`;
const HASH_PREFIX = `${CHANGELOG_URL}#`;

async function gotoChangelog(page: Page): Promise<string[]> {
  const errors: string[] = [];
  page.on('pageerror', (e) => {
    const msg = `pageerror: ${e.message}`;
    if (!isIgnorable(msg)) errors.push(msg);
  });
  const response = await page.goto('/changelog', { waitUntil: 'domcontentloaded' });
  expect(response, 'no response for /changelog').not.toBeNull();
  expect(response!.status(), `/changelog returned ${response!.status()}`).toBeLessThan(400);
  await expect
    .poll(() => page.evaluate(() => document.getElementById('root')?.innerHTML.length ?? 0), {
      timeout: 10_000,
    })
    .toBeGreaterThan(500);
  return errors;
}

async function readJsonLdBlocks(page: Page): Promise<{ raw: string; data: unknown }[]> {
  // Poll until Helmet has appended its JSON-LD scripts (they land after hydration).
  await expect
    .poll(
      () =>
        page.$$eval('script[type="application/ld+json"]', (nodes) => nodes.length),
      { timeout: 10_000 },
    )
    .toBeGreaterThan(0);
  const raws = await page.$$eval('script[type="application/ld+json"]', (nodes) =>
    nodes.map((n) => n.textContent ?? ''),
  );
  return raws.map((raw) => ({ raw, data: JSON.parse(raw) as unknown }));
}

type ListItem = {
  '@type': string;
  position?: number;
  name?: string;
  url?: string;
};
type ItemList = {
  '@context'?: string;
  '@type': string;
  name?: string;
  description?: string;
  numberOfItems?: number;
  itemListOrder?: string;
  itemListElement?: ListItem[];
};
type BreadcrumbItem = { '@type': string; position?: number; name?: string; item?: string };
type Breadcrumb = {
  '@context'?: string;
  '@type': string;
  itemListElement?: BreadcrumbItem[];
};

const isItemList = (d: unknown): d is ItemList =>
  typeof d === 'object' &&
  d !== null &&
  (d as { '@type'?: unknown })['@type'] === 'ItemList';

const isBreadcrumb = (d: unknown): d is Breadcrumb =>
  typeof d === 'object' &&
  d !== null &&
  (d as { '@type'?: unknown })['@type'] === 'BreadcrumbList';

// Box 1: exactly one top-level ItemList block is emitted on /changelog with
// the required fields. Its description mirrors the Helmet meta description
// (asserted byte-for-byte in Box 5). The /demos hub's SoftwareApplication
// block's nested mainEntity does not count - it lives at a different URL and
// this spec is URL-scoped to /changelog.
test('emits exactly one ItemList JSON-LD block with the required fields', async ({ page }) => {
  const errors = await gotoChangelog(page);
  const blocks = await readJsonLdBlocks(page);
  const lists = blocks.filter((b): b is { raw: string; data: ItemList } => isItemList(b.data));
  expect(lists, 'exactly one top-level ItemList block expected on /changelog').toHaveLength(1);

  const list = lists[0].data;
  expect(list['@context']).toBe('https://schema.org');
  expect(list['@type']).toBe('ItemList');
  expect(list.name).toBe('Digital Craft AI Changelog');
  expect(typeof list.description).toBe('string');
  expect((list.description ?? '').length).toBeGreaterThan(20);
  expect(list.itemListOrder).toBe('https://schema.org/ItemListOrderDescending');
  expect(typeof list.numberOfItems).toBe('number');
  expect((list.numberOfItems ?? 0)).toBeGreaterThan(0);
  expect(Array.isArray(list.itemListElement)).toBe(true);

  // Round-trip parse so a future stringify bug fails here.
  expect(() => JSON.parse(lists[0].raw)).not.toThrow();
  expect(errors).toEqual([]);
});

// Box 2: ItemList.itemListElement length equals the number of rendered
// changelog entries on the page (the existing VISIBLE_LIMIT=36 cap from
// src/pages/Changelog.tsx). Both derive from the same sliced array, so the
// schema length tracks the rendered length automatically. Also asserts
// numberOfItems === itemListElement.length.
test('itemListElement length equals the rendered changelog row count', async ({ page }) => {
  const errors = await gotoChangelog(page);
  const blocks = await readJsonLdBlocks(page);
  const lists = blocks.filter((b): b is { raw: string; data: ItemList } => isItemList(b.data));
  expect(lists).toHaveLength(1);

  const list = lists[0].data;
  const items = list.itemListElement ?? [];

  // Schema self-consistency.
  expect(list.numberOfItems).toBe(items.length);

  // Visible-row parity with the page render.
  const renderedCount = await page.locator('[data-testid="changelog-entry"]').count();
  expect(renderedCount, 'page should render at least one changelog entry').toBeGreaterThan(0);
  expect(items.length).toBe(renderedCount);

  expect(errors).toEqual([]);
});

// Box 3: every ListItem has @type === 'ListItem', a positive integer position,
// a non-empty name, and a url that starts with
// https://digitalcraftai.com/changelog#. The first entry's position is 1 and
// its name matches the first rendered entry's title.
test('every ListItem is well-formed and the first matches the first rendered row', async ({ page }) => {
  const errors = await gotoChangelog(page);
  const blocks = await readJsonLdBlocks(page);
  const lists = blocks.filter((b): b is { raw: string; data: ItemList } => isItemList(b.data));
  expect(lists).toHaveLength(1);

  const items = lists[0].data.itemListElement ?? [];
  expect(items.length).toBeGreaterThan(0);

  for (const it of items) {
    expect(it['@type']).toBe('ListItem');
    expect(typeof it.position).toBe('number');
    expect(Number.isInteger(it.position)).toBe(true);
    expect((it.position ?? 0)).toBeGreaterThan(0);
    expect(typeof it.name).toBe('string');
    expect((it.name ?? '').length).toBeGreaterThan(0);
    expect(typeof it.url).toBe('string');
    expect((it.url ?? '').startsWith(HASH_PREFIX)).toBe(true);
  }

  // First entry: position 1 (newest-first ordering).
  expect(items[0].position).toBe(1);

  // First rendered entry's title must equal items[0].name.
  const firstRowTitle = await page
    .locator('[data-testid="changelog-entry"]')
    .first()
    .locator('p')
    .first()
    .textContent();
  expect((firstRowTitle ?? '').trim()).toBe(items[0].name);

  expect(errors).toEqual([]);
});

// Box 4: a BreadcrumbList block (Home -> Changelog) is also emitted on
// /changelog. Per-URL scoped; no predecessor spec asserts site-wide
// BreadcrumbList uniqueness (pre-write grep result documented on the ticket).
test('emits exactly one BreadcrumbList JSON-LD block naming Changelog', async ({ page }) => {
  const errors = await gotoChangelog(page);
  const blocks = await readJsonLdBlocks(page);
  const breadcrumbs = blocks.filter((b): b is { raw: string; data: Breadcrumb } =>
    isBreadcrumb(b.data),
  );
  expect(breadcrumbs, 'exactly one BreadcrumbList block expected on /changelog').toHaveLength(1);

  const items = breadcrumbs[0].data.itemListElement ?? [];
  expect(items.length).toBe(2);
  expect((items[0].name ?? '').toLowerCase()).toBe('home');
  expect(items[0].item).toBe(ORIGIN);
  expect(items[1].name).toBe('Changelog');
  expect(items[1].item).toBe(CHANGELOG_URL);

  expect(() => JSON.parse(breadcrumbs[0].raw)).not.toThrow();
  expect(errors).toEqual([]);
});

// Box 5: the meta[name="description"] content equals the ItemList block's
// description byte-for-byte (mirror-source guarantee). Reads the LAST
// meta[name="description"] element per the 2026-05-25 Helmet-appends lesson.
test('ItemList description mirrors the Helmet meta[name="description"] byte-for-byte', async ({
  page,
}) => {
  const errors = await gotoChangelog(page);

  await expect
    .poll(
      () =>
        page
          .locator('head meta[name="description"]')
          .evaluateAll((nodes) => nodes.map((n) => (n as HTMLMetaElement).content)),
      { timeout: 10_000 },
    )
    .toEqual(expect.arrayContaining([expect.stringMatching(/.+/)]));

  const descriptions = await page
    .locator('head meta[name="description"]')
    .evaluateAll((nodes) => nodes.map((n) => (n as HTMLMetaElement).content));
  // Read the LAST meta[name="description"] (the Helmet-appended one, not the
  // index.html default that may land earlier). Per the 2026-05-25
  // Helmet-appends lesson.
  const helmetDescription = descriptions[descriptions.length - 1];
  expect(typeof helmetDescription).toBe('string');
  expect(helmetDescription.length).toBeGreaterThan(20);
  expect(helmetDescription).not.toContain(EM_DASH);

  const blocks = await readJsonLdBlocks(page);
  const lists = blocks.filter((b): b is { raw: string; data: ItemList } => isItemList(b.data));
  expect(lists).toHaveLength(1);
  expect(lists[0].data.description).toBe(helmetDescription);

  expect(errors).toEqual([]);
});

// Box 6: page renders in light AND dark mode on a 375px mobile viewport, the
// blocks parse as valid JSON, and the JSON-LD blocks this PR emits contain
// zero em-dash characters (U+2014). The visible /changelog main copy is also
// em-dash-free (mirror-source-fix guarantee per 2026-05-25).
test('renders in light/dark on mobile and emits no em-dash in the JSON-LD', async ({ page }) => {
  const errors = await gotoChangelog(page);
  await page.setViewportSize({ width: 375, height: 812 });
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible();

  // Dark mode: toggle .dark on the root, the page still renders.
  await page.evaluate(() => document.documentElement.classList.add('dark'));
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible();

  const blocks = await readJsonLdBlocks(page);
  const ours = blocks.filter((b) => isItemList(b.data) || isBreadcrumb(b.data));
  expect(ours.length, 'ItemList + BreadcrumbList blocks must both render').toBe(2);
  for (const b of ours) {
    expect(() => JSON.parse(b.raw)).not.toThrow();
    expect(b.raw, `JSON-LD block contains em-dash: ${b.raw}`).not.toContain(EM_DASH);
  }

  // Visible /changelog <main> copy also has no em-dash (mirror-source-fix
  // guarantee per the 2026-05-25 lesson).
  const visibleMain = await page.locator('main').innerText();
  expect(visibleMain, 'visible /changelog <main> copy contains an em-dash').not.toContain(EM_DASH);

  expect(errors).toEqual([]);
});

// Box 7: no copy regression. The H1 still reads the documented literal, and
// the demo-link resolver still emits at least one "Try the demo" link for
// area === 'demos' entries (the ticket-0032 contract).
test('preserves the H1 and the demos-area "Try the demo" link affordance', async ({ page }) => {
  const errors = await gotoChangelog(page);

  const h1 = page.getByRole('heading', { level: 1 });
  await expect(h1).toBeVisible();
  expect(((await h1.textContent()) ?? '').trim()).toBe('What we shipped lately');

  // At least one "Try the demo" link remains on the page (ticket 0032's
  // demo-link resolver behavior).
  const tryDemoLinks = page.getByRole('link', { name: /try the demo/i });
  expect(await tryDemoLinks.count()).toBeGreaterThan(0);

  expect(errors).toEqual([]);
});

// Box 8: rendering the JSON-LD makes no first-party /api/ call (the schema is
// fully static, derived from the already-bundled changelogEntries array at
// render time, so it must not introduce any new data flow).
test('renders the schema with no first-party /api/ call', async ({ page }) => {
  const apiCalls: string[] = [];
  await gotoChangelog(page);
  const appOrigin = new URL(page.url()).origin;
  page.on('request', (req) => {
    const u = new URL(req.url());
    if (u.origin === appOrigin && u.pathname.startsWith('/api/')) apiCalls.push(req.url());
  });

  const blocks = await readJsonLdBlocks(page);
  const lists = blocks.filter((b) => isItemList(b.data));
  expect(lists).toHaveLength(1);

  expect(
    apiCalls,
    `rendering /changelog JSON-LD should make no first-party /api/ call:\n${apiCalls.join('\n')}`,
  ).toEqual([]);
});
