import { test, expect, type Page } from '@playwright/test';
import { IGNORABLE_ERROR_PATTERNS } from './routes';

// Ticket 0055 - Public /changelog/rss.xml RSS 2.0 feed of shipped tickets.
// Each test maps 1:1 to one of the eight checks in acceptance criterion #7.
//
// The feed is generated at build time by scripts/generate-changelog-rss.ts
// (invoked from scripts/generate-changelog.ts, which is itself invoked from
// scripts/generate-sitemap.ts at the start of `npm run build`). The feed
// reads from src/data/changelogEntries.ts (auto-generated by ticket 0032's
// scripts/generate-changelog.ts from docs/backlog/*.md frontmatter).
//
// Per the 2026-05-25 SEO Pilot lesson, this spec does NOT call
// page.toHaveTitle() for /changelog - that route is not in the index.html
// SEO Pilot table. The HTML-side assertion (check 8) reads the
// Helmet-emitted <link rel="alternate"> directly.

const isIgnorable = (msg: string) =>
  IGNORABLE_ERROR_PATTERNS.some((re) => re.test(msg));

// U+2014 spelled via fromCharCode so this file itself contains no em-dash
// (the brand-voice Hard NO bans the literal character even in tests).
const EM_DASH = String.fromCharCode(8212);

const FEED_PATH = '/changelog/rss.xml';
const FEED_URL_PATTERN = /^https:\/\/digitalcraftai\.com\/changelog#\d{4}$/;

async function fetchFeed(request: Page['request']): Promise<{
  status: number;
  contentType: string;
  body: string;
}> {
  const res = await request.get(FEED_PATH);
  return {
    status: res.status(),
    contentType: res.headers()['content-type'] ?? '',
    body: await res.text(),
  };
}

// Box 1: GET /changelog/rss.xml returns 200 and content-type contains 'xml'.
test('GET /changelog/rss.xml returns 200 and an xml content-type', async ({
  request,
}) => {
  const { status, contentType, body } = await fetchFeed(request);
  expect(status, `expected 200 for ${FEED_PATH}, got ${status}`).toBe(200);
  expect(contentType.toLowerCase()).toContain('xml');
  expect(body.length, 'feed body must be non-empty').toBeGreaterThan(200);
  expect(body.startsWith('<?xml')).toBe(true);
});

// Box 2: exactly one <channel> block in the feed.
test('feed has exactly one <channel> block', async ({ request }) => {
  const { body } = await fetchFeed(request);
  const channelOpens = body.match(/<channel>/g) ?? [];
  const channelCloses = body.match(/<\/channel>/g) ?? [];
  expect(channelOpens.length, 'expected exactly one <channel> open tag').toBe(1);
  expect(channelCloses.length, 'expected exactly one </channel> close tag').toBe(1);
});

// Box 3: channel block has <title>, <link>, <description>, <language>, and
// an Atom <atom:link rel="self"> self-link.
test('channel block has title, link, description, language, and atom:link self', async ({
  request,
}) => {
  const { body } = await fetchFeed(request);
  const channelMatch = body.match(/<channel>([\s\S]*?)<\/channel>/);
  expect(channelMatch, 'feed must contain a <channel>...</channel> block').not.toBeNull();
  const channel = channelMatch![1];

  // Strip <item> blocks so the channel-level tag checks do not see item
  // children.
  const channelMeta = channel.replace(/<item>[\s\S]*?<\/item>/g, '');

  expect(channelMeta).toMatch(/<title>[^<]+<\/title>/);
  expect(channelMeta).toMatch(/<link>https:\/\/digitalcraftai\.com\/changelog<\/link>/);
  expect(channelMeta).toMatch(/<description>[^<]+<\/description>/);
  expect(channelMeta).toMatch(/<language>en-us<\/language>/);
  expect(channelMeta).toMatch(
    /<atom:link[^/>]*href="https:\/\/digitalcraftai\.com\/changelog\/rss\.xml"[^/>]*rel="self"[^/>]*\/>|<atom:link[^/>]*rel="self"[^/>]*href="https:\/\/digitalcraftai\.com\/changelog\/rss\.xml"[^/>]*\/>/,
  );
});

// Box 4: at least one <item> block; each <item> has all six required
// children: title, link, guid, pubDate, description, category.
test('at least one <item> with all six required children', async ({ request }) => {
  const { body } = await fetchFeed(request);
  const items = body.match(/<item>[\s\S]*?<\/item>/g) ?? [];
  expect(items.length, 'feed must contain at least one <item>').toBeGreaterThan(0);

  for (const item of items) {
    expect(item, `<item> missing <title>: ${item}`).toMatch(/<title>[^<]+<\/title>/);
    expect(item, `<item> missing <link>: ${item}`).toMatch(/<link>[^<]+<\/link>/);
    expect(item, `<item> missing <guid>: ${item}`).toMatch(/<guid[^>]*>[^<]+<\/guid>/);
    expect(item, `<item> missing <pubDate>: ${item}`).toMatch(/<pubDate>[^<]+<\/pubDate>/);
    expect(item, `<item> missing <description>: ${item}`).toMatch(/<description>[^<]+<\/description>/);
    expect(item, `<item> missing <category>: ${item}`).toMatch(/<category>[^<]+<\/category>/);
  }
});

// Box 5: every <pubDate> parses as a valid Date.
test('every <pubDate> parses as a valid Date', async ({ request }) => {
  const { body } = await fetchFeed(request);
  const pubDates = [...body.matchAll(/<pubDate>([^<]+)<\/pubDate>/g)].map((m) => m[1]);
  expect(pubDates.length, 'feed must have at least one <pubDate>').toBeGreaterThan(0);
  for (const dateStr of pubDates) {
    const parsed = new Date(dateStr);
    expect(
      Number.isFinite(parsed.getTime()),
      `<pubDate>${dateStr}</pubDate> did not parse as a valid Date`,
    ).toBe(true);
  }
});

// Box 6: every per-item <link> matches the changelog-anchor permalink shape.
test('every item <link> is a /changelog#NNNN permalink', async ({ request }) => {
  const { body } = await fetchFeed(request);
  const items = body.match(/<item>[\s\S]*?<\/item>/g) ?? [];
  expect(items.length).toBeGreaterThan(0);
  for (const item of items) {
    const linkMatch = item.match(/<link>([^<]+)<\/link>/);
    expect(linkMatch, `<item> missing <link>: ${item}`).not.toBeNull();
    const linkValue = linkMatch![1];
    expect(
      FEED_URL_PATTERN.test(linkValue),
      `<link>${linkValue}</link> does not match ${FEED_URL_PATTERN}`,
    ).toBe(true);
  }
});

// Box 7: feed body contains zero U+2014 em-dash code points.
test('feed body contains zero em-dash (U+2014) code points', async ({ request }) => {
  const { body } = await fetchFeed(request);
  expect(body, 'feed body must not contain the em-dash character').not.toContain(EM_DASH);
});

// Box 8: /changelog HTML page has <link rel="alternate" type="application/rss+xml">
// pointing at the feed URL, for auto-discovery by browsers and feedreaders.
test('/changelog HTML page advertises the RSS feed via <link rel="alternate">', async ({
  page,
}) => {
  const errors: string[] = [];
  page.on('pageerror', (e) => {
    const msg = `pageerror: ${e.message}`;
    if (!isIgnorable(msg)) errors.push(msg);
  });
  const response = await page.goto('/changelog', { waitUntil: 'domcontentloaded' });
  expect(response).not.toBeNull();
  expect(response!.status()).toBeLessThan(400);

  // Poll until Helmet appends the link tag.
  await expect
    .poll(
      () =>
        page
          .locator('head link[rel="alternate"][type="application/rss+xml"]')
          .count(),
      { timeout: 10_000 },
    )
    .toBeGreaterThan(0);

  const href = await page
    .locator('head link[rel="alternate"][type="application/rss+xml"]')
    .first()
    .getAttribute('href');
  expect(href).not.toBeNull();
  expect(href!.endsWith('/changelog/rss.xml')).toBe(true);

  expect(errors).toEqual([]);
});
