// All static routes from src/App.tsx. Dynamic-param routes (:slug etc.) are
// excluded — add a dedicated test if you need to cover them with real slugs.
// Keep this list in sync when adding new routes; the agent will fail the
// smoke gate if it adds a route here without it actually rendering.
export const ROUTES: readonly string[] = [
  '/',
  '/construction',
  '/construction/demo',
  '/construction/demo/lead-responder',
  '/construction/demo/estimate',
  '/construction/demo/invoice',
  '/construction/demo/sms-sequence',
  '/construction/demo/lead-scoring',
  '/construction/demo/reviews',
  '/construction/demo/property-negotiator',
  '/construction/demo/voice-negotiator',
  '/realestate',
  '/realestate/demo',
  '/realestate/demo/lead-responder',
  '/realestate/demo/property-negotiator',
  '/realestate/demo/contract',
  '/realestate/demo/market-analysis',
  '/realestate/demo/voice-negotiator',
  '/events',
  '/events/demo',
  '/events/demo/inquiry',
  '/events/demo/proposal',
  '/events/demo/voice-booking',
  '/homeservices',
  '/homeservices/demo',
  '/homeservices/demo/lead-responder',
  '/homeservices/demo/estimate',
  '/homeservices/demo/voice-followup',
  '/healthcare',
  '/healthcare/demo',
  '/healthcare/demo/intake',
  '/healthcare/demo/scheduler',
  '/healthcare/demo/voice-followup',
  '/legal',
  '/legal/demo',
  '/legal/demo/intake',
  '/legal/demo/consultation',
  '/legal/demo/voice-followup',
  '/restaurant',
  '/restaurant/demo',
  '/restaurant/demo/reservations',
  '/restaurant/demo/catering',
  '/restaurant/demo/reviews',
  '/kidsplay',
  '/kidsplay/demo',
  '/kidsplay/demo/party-booker',
  '/kidsplay/demo/packages',
  '/kidsplay/demo/voice-booking',
  '/fitness',
  '/fitness/demo',
  '/fitness/demo/lead-qualifier',
  '/fitness/demo/membership',
  '/fitness/demo/voice-retention',
  '/dental',
  '/dental/demo',
  '/dental/demo/intake',
  '/dental/demo/estimate',
  '/dental/demo/voice-recall',
  '/salon',
  '/salon/demo',
  '/salon/demo/booking',
  '/salon/demo/services',
  '/salon/demo/voice-rebook',
  '/autorepair',
  '/autorepair/demo',
  '/autorepair/demo/advisor',
  '/autorepair/demo/estimate',
  '/autorepair/demo/voice-reminder',
  '/industries',
  '/demos',
  '/glossary',
  '/trust',
  '/compare/hubspot',
  '/compare/gohighlevel',
  '/compare/zapier',
  '/compare/make',
  '/compare/intercom',
  '/compare/jobber',
  '/compare/servicetitan',
  '/quiz',
  '/setupclaw',
  '/ai-for-small-business',
  '/ai-for-plumbers',
  '/ai-for-hvac',
  '/ai-for-roofers',
  '/locations/texas',
  '/blog',
  '/classes',
  '/classes/register',
];

// Uncaught exceptions we accept in test env — third-party SDKs that can't
// init without real keys. Keep this list tight; every entry is a known blind
// spot the smoke gate will NOT catch.
export const IGNORABLE_ERROR_PATTERNS: readonly RegExp[] = [
  /vapi/i,    // Vapi SDK absent VAPI_PUBLIC_KEY
  /sentry/i,  // Sentry init without DSN
];
