import React from 'react';
import { Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import ScrollProgress from '@/components/ScrollProgress';
import { useContent } from '@/hooks/useContent';
import { trackCTAClick } from '@/utils/analytics';
import { KNOWN_PATHS } from '@/utils/recentDemosStore';
import { changelogEntries, type ChangelogEntry, type ChangelogArea } from '@/data/changelogEntries';
import { Rss, ArrowRight } from 'lucide-react';

// Ticket 0032 - Public /changelog page surfacing weekly ship velocity.
//
// Renders the latest VISIBLE_LIMIT shipped backlog tickets, grouped by
// month-year, with an area chip and a "Try the demo" link for area === 'demos'
// rows that resolve to a route in KNOWN_PATHS (src/utils/recentDemosStore.ts).
//
// Per the 2026-05-25 SEO Pilot lesson, /changelog is NOT in the index.html
// SEO Pilot pages table, so document.title falls back to homepage title on
// SPA navigation; the e2e spec asserts the Helmet-managed
// meta[name="description"] directly, not toHaveTitle. Adding /changelog to
// the SEO Pilot table is its own SEO concern, out of scope here.
//
// Per the 2026-05-25 mirror-source lesson, the page reads from
// src/data/changelogEntries.ts which is regenerated by
// scripts/generate-changelog.ts at build time (invoked from
// scripts/generate-sitemap.ts so the build chain edit stays out of
// package.json - the GTM queue Hard NO). The demo-link resolver consults the
// same KNOWN_PATHS allow-list that ticket 0026 and 0027 use, so a renamed
// demo cannot strand a dead link from this page.

const VISIBLE_LIMIT = 36;

const CHANGELOG_DESCRIPTION =
  'Recent ships from the Digital Craft AI team. Dated, grouped by month, sourced directly from the public backlog so you can see what we shipped this week without checking LinkedIn.';

// Ticket 0043 - BreadcrumbList JSON-LD (Home -> Changelog) emitted inside the
// existing Helmet head, matching the pattern in src/pages/AiForElectricians.tsx
// and src/pages/compare/Podium.tsx. The block is a module-level constant
// because the breadcrumb shape is fixed.
const BREADCRUMB_SCHEMA = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://digitalcraftai.com' },
    {
      '@type': 'ListItem',
      position: 2,
      name: 'Changelog',
      item: 'https://digitalcraftai.com/changelog',
    },
  ],
};

// Ticket 0043 - Build an ItemList JSON-LD object from the SAME sliced array
// the page renders, so the schema length tracks the rendered length exactly
// (mirror-source rule from the 2026-05-25 lesson). Each ListItem derives its
// name from entry.title and its url from the per-entry hash anchor on the
// page (id={entry.id} on each row, added below). itemListOrder reflects the
// newest-first order the generator emits and the page preserves.
function buildItemListSchema(entries: readonly ChangelogEntry[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    name: 'Digital Craft AI Changelog',
    description: CHANGELOG_DESCRIPTION,
    numberOfItems: entries.length,
    itemListOrder: 'https://schema.org/ItemListOrderDescending',
    itemListElement: entries.map((entry, index) => ({
      '@type': 'ListItem',
      position: index + 1,
      name: entry.title,
      url: `https://digitalcraftai.com/changelog#${entry.id}`,
    })),
  };
}

// Tailwind chip colors per area. Every variant carries a `dark:` pair
// (AGENTS.md Hard NO). Areas are constrained to the seven values in the
// generator's VALID_AREAS set, so this map is exhaustive.
const AREA_CHIP: Record<ChangelogArea, string> = {
  conversion: 'bg-emerald-50 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300',
  seo: 'bg-blue-50 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300',
  content: 'bg-amber-50 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300',
  trust: 'bg-violet-50 text-violet-700 dark:bg-violet-900/30 dark:text-violet-300',
  demos: 'bg-sky-50 text-sky-700 dark:bg-sky-900/30 dark:text-sky-300',
  infra: 'bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-300',
  perf: 'bg-rose-50 text-rose-700 dark:bg-rose-900/30 dark:text-rose-300',
};

// Tokens that are too generic to drive a demo-link match. Keeps the resolver
// from snapping "Shareable branded voice-call summary link" onto any
// /demo path just because it contains the word "demo".
const STOPWORDS = new Set([
  'a', 'an', 'and', 'on', 'in', 'for', 'the', 'to', 'with', 'of', 'as', 'at',
  'demo', 'demos', 'page', 'link', 'cta', 'screen', 'screens', 'each',
  'new', 'public', 'visible', 'every', 'into', 'across',
]);

function tokens(s: string): string[] {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, ' ')
    .split(/\s+/)
    .filter((t) => t.length >= 4 && !STOPWORDS.has(t));
}

/**
 * Resolve a demos-area entry to the first KNOWN_PATHS route whose final path
 * segment shares a meaningful token with the title. Returns null if no
 * confident match exists - the page omits the "Try the demo" link rather
 * than guess and strand the visitor on a wrong demo. The 2026-05-25 mirror-
 * source lesson: KNOWN_PATHS is the single allow-list both store and page
 * consult, so a renamed demo cannot strand a dead link from /changelog.
 */
function resolveDemoPath(title: string): string | null {
  const titleTokens = new Set(tokens(title));
  if (titleTokens.size === 0) return null;
  for (const path of KNOWN_PATHS) {
    const lastSegment = path.split('/').pop() ?? '';
    const segmentTokens = lastSegment.split('-').filter((t) => t.length >= 4);
    for (const tok of segmentTokens) {
      if (titleTokens.has(tok)) return path;
    }
  }
  return null;
}

interface MonthGroup {
  key: string; // YYYY-MM
  label: string; // "June 2026"
  entries: ChangelogEntry[];
}

function formatMonth(yyyymm: string): string {
  const [y, m] = yyyymm.split('-').map(Number);
  // UTC to avoid TZ skew flipping a month boundary.
  const d = new Date(Date.UTC(y, (m ?? 1) - 1, 1));
  return d.toLocaleDateString('en-US', { month: 'long', year: 'numeric', timeZone: 'UTC' });
}

function groupByMonth(entries: readonly ChangelogEntry[]): MonthGroup[] {
  const map = new Map<string, ChangelogEntry[]>();
  for (const e of entries) {
    const key = e.created.slice(0, 7);
    const bucket = map.get(key) ?? [];
    bucket.push(e);
    map.set(key, bucket);
  }
  return [...map.entries()]
    .sort((a, b) => b[0].localeCompare(a[0]))
    .map(([key, list]) => ({ key, label: formatMonth(key), entries: list }));
}

const Changelog: React.FC = () => {
  const { content } = useContent();
  const visible = changelogEntries.slice(0, VISIBLE_LIMIT);
  const groups = groupByMonth(visible);
  const totalShipped = visible.length;
  const itemListSchema = buildItemListSchema(visible);

  return (
    <div className="min-h-screen bg-white dark:bg-gray-950">
      <Helmet>
        <title>Changelog | Recent Ships | DigitalCraft AI</title>
        <meta name="description" content={CHANGELOG_DESCRIPTION} />
        <link rel="canonical" href="https://digitalcraftai.com/changelog" />
        <meta property="og:title" content="Changelog | DigitalCraft AI" />
        <meta property="og:description" content={CHANGELOG_DESCRIPTION} />
        <meta property="og:url" content="https://digitalcraftai.com/changelog" />
        <script type="application/ld+json">{JSON.stringify(itemListSchema)}</script>
        <script type="application/ld+json">{JSON.stringify(BREADCRUMB_SCHEMA)}</script>
      </Helmet>
      <Navbar />
      <ScrollProgress />

      <main>
        <section className="pt-32 pb-10 bg-gradient-to-br from-gray-50 to-white dark:from-gray-900 dark:to-gray-950">
          <div className="container mx-auto px-4 text-center max-w-3xl">
            <div className="inline-flex items-center gap-2 px-4 py-2 bg-primary/10 dark:bg-primary/20 rounded-full text-primary text-sm font-medium mb-6">
              <Rss size={16} />
              Recent ships
            </div>
            <h1 className="text-4xl md:text-5xl font-bold mb-5 text-gray-900 dark:text-white">
              What we shipped lately
            </h1>
            <p className="text-lg text-gray-600 dark:text-gray-300 max-w-2xl mx-auto">
              Every row is a real ticket from our public backlog with a date
              you can verify. The latest {totalShipped} ships, grouped by month.
            </p>
          </div>
        </section>

        {groups.length > 0 && (
          <section className="py-6 bg-white dark:bg-gray-950 border-b border-gray-100 dark:border-gray-800">
            <div className="container mx-auto px-4 max-w-5xl">
              <div className="flex flex-wrap gap-2 justify-center">
                {groups.map((g) => (
                  <a
                    key={g.key}
                    href={`#month-${g.key}`}
                    className="text-xs px-3 py-1 rounded-full border border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-400 hover:border-primary hover:text-primary dark:hover:border-primary dark:hover:text-primary transition-colors"
                  >
                    {g.label} ({g.entries.length})
                  </a>
                ))}
              </div>
            </div>
          </section>
        )}

        <section className="py-12 bg-white dark:bg-gray-950">
          <div className="container mx-auto px-4 max-w-3xl">
            <div className="space-y-12">
              {groups.map((g) => (
                <article key={g.key} id={`month-${g.key}`} className="scroll-mt-28">
                  <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4 border-b border-gray-200 dark:border-gray-800 pb-2">
                    {g.label}
                    <span className="ml-3 text-sm font-normal text-gray-500 dark:text-gray-400">
                      {g.entries.length} {g.entries.length === 1 ? 'ship' : 'ships'}
                    </span>
                  </h2>
                  <ul className="space-y-3">
                    {g.entries.map((entry) => {
                      const demoPath = entry.area === 'demos' ? resolveDemoPath(entry.title) : null;
                      return (
                        <li
                          key={entry.id}
                          id={entry.id}
                          data-testid="changelog-entry"
                          className="flex flex-col sm:flex-row sm:items-start gap-2 sm:gap-4 p-4 rounded-lg border border-gray-200 dark:border-gray-800 bg-gray-50/50 dark:bg-gray-900/40 hover:border-primary/40 dark:hover:border-primary/40 transition-colors scroll-mt-28"
                        >
                          <div className="flex items-center gap-3 shrink-0 sm:w-44">
                            <code className="text-xs font-mono px-2 py-0.5 rounded bg-gray-200 dark:bg-gray-800 text-gray-700 dark:text-gray-300">
                              {entry.id}
                            </code>
                            <span className="text-xs text-gray-500 dark:text-gray-400 font-mono">
                              {entry.created}
                            </span>
                          </div>
                          <div className="flex-1 min-w-0">
                            <p className="text-sm sm:text-base text-gray-900 dark:text-gray-100 leading-snug">
                              {entry.title}
                            </p>
                            <div className="mt-2 flex flex-wrap items-center gap-2">
                              <span
                                className={`text-xs px-2 py-0.5 rounded-full font-medium ${AREA_CHIP[entry.area]}`}
                              >
                                {entry.area}
                              </span>
                              {demoPath && (
                                <Link
                                  to={demoPath}
                                  onClick={() => trackCTAClick('changelog_demo_jump', entry.id)}
                                  className="inline-flex items-center gap-1 text-xs text-primary hover:underline"
                                >
                                  Try the demo
                                  <ArrowRight size={12} />
                                </Link>
                              )}
                            </div>
                          </div>
                        </li>
                      );
                    })}
                  </ul>
                </article>
              ))}
            </div>
          </div>
        </section>

        <section className="py-16 bg-gray-50 dark:bg-gray-900">
          <div className="container mx-auto px-4 text-center max-w-2xl">
            <h2 className="text-2xl md:text-3xl font-bold mb-4 text-gray-900 dark:text-white">
              Like the cadence? Try the demos these tickets shipped.
            </h2>
            <p className="text-gray-600 dark:text-gray-300 mb-8">
              The page above is the receipt. The demos below are what the tickets actually built.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link
                to="/demos"
                onClick={() => trackCTAClick('view_demos', 'changelog_cta')}
                className="inline-flex items-center justify-center gap-2 px-6 py-3 bg-primary hover:bg-primary/90 text-white rounded-lg font-medium transition-colors"
              >
                Browse the Demos
                <ArrowRight size={18} />
              </Link>
              <Link
                to="/trust"
                onClick={() => trackCTAClick('view_trust', 'changelog_cta')}
                className="inline-flex items-center justify-center gap-2 px-6 py-3 border border-gray-300 dark:border-gray-700 text-gray-700 dark:text-gray-300 hover:border-primary hover:text-primary dark:hover:border-primary dark:hover:text-primary rounded-lg font-medium transition-colors"
              >
                How the demos handle your data
              </Link>
            </div>
          </div>
        </section>
      </main>

      {content?.footer && <Footer data={content.footer} />}
    </div>
  );
};

export default Changelog;
