import { readdirSync, readFileSync, writeFileSync } from "fs";
import { join, relative } from "path";

// Ticket 0032 - Public /changelog page generator.
//
// Reads every docs/backlog/*.md file at build time, parses the YAML
// frontmatter between the leading `---` and the next `---` line with a
// small hand-rolled regex (no new dependency - the GTM queue Hard NO bans
// touching package.json), filters to status === 'shipped', sorts by
// `created` descending, validates dates, and writes a typed
// src/data/changelogEntries.ts array.
//
// Per the 2026-05-28 inline-assertion-in-the-gated-script lesson, this
// script encodes its own assertions: missing `created`, invalid
// `YYYY-MM-DD`, future date, or duplicate id throws and fails the build.
// A `src/data/changelogEntries.ts.broken` artifact is saved on failure.
//
// This script is invoked from scripts/generate-sitemap.ts (already in the
// `npm run build` chain) so no package.json edit is required. The
// generated file IS committed (not gitignored) so typecheck and lint see
// a real typed import without needing the generator to run first.

const ROOT = join(import.meta.dirname, "..");
const BACKLOG_DIR = join(ROOT, "docs", "backlog");
const OUT_PATH = join(ROOT, "src", "data", "changelogEntries.ts");
const BROKEN_PATH = OUT_PATH + ".broken";

export type ChangelogArea =
  | "conversion"
  | "seo"
  | "content"
  | "trust"
  | "demos"
  | "infra"
  | "perf";

export interface ChangelogEntry {
  id: string;
  title: string;
  area: ChangelogArea;
  created: string; // YYYY-MM-DD
}

const VALID_AREAS: ReadonlySet<string> = new Set([
  "conversion", "seo", "content", "trust", "demos", "infra", "perf",
]);

const DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

function todayYmd(): string {
  return new Date().toISOString().split("T")[0];
}

// Strip optional surrounding single or double quotes from a frontmatter
// value (some ticket titles are quoted because they start with `"`).
function unquote(raw: string): string {
  const trimmed = raw.trim();
  if (
    (trimmed.startsWith('"') && trimmed.endsWith('"')) ||
    (trimmed.startsWith("'") && trimmed.endsWith("'"))
  ) {
    return trimmed.slice(1, -1);
  }
  return trimmed;
}

function parseFrontmatter(text: string): Record<string, string> | null {
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) return null;
  const out: Record<string, string> = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^([a-zA-Z_][a-zA-Z0-9_-]*)\s*:\s*(.*)$/);
    if (!kv) continue;
    out[kv[1]] = unquote(kv[2]);
  }
  return out;
}

interface CollectResult {
  entries: ChangelogEntry[];
  problems: string[];
}

function collectEntries(): CollectResult {
  const problems: string[] = [];
  const entries: ChangelogEntry[] = [];
  const seenIds = new Set<string>();
  const today = todayYmd();

  const files = readdirSync(BACKLOG_DIR)
    .filter((f) => /^\d{4}-.*\.md$/.test(f))
    .sort();

  for (const name of files) {
    const fullPath = join(BACKLOG_DIR, name);
    const text = readFileSync(fullPath, "utf-8");
    const fm = parseFrontmatter(text);
    const rel = relative(ROOT, fullPath);

    if (!fm) {
      problems.push(`${rel}: missing or malformed frontmatter block`);
      continue;
    }
    const status = fm.status;
    if (status !== "shipped") continue; // proposed/groomed/in-progress/rejected are skipped silently

    const id = fm.id;
    const title = fm.title;
    const area = fm.area;
    const created = fm.created;

    if (!id || !/^\d{4}$/.test(id)) {
      problems.push(`${rel}: shipped ticket has invalid id "${id}"`);
      continue;
    }
    if (seenIds.has(id)) {
      problems.push(`${rel}: duplicate shipped id ${id}`);
      continue;
    }
    if (!title) {
      problems.push(`${rel}: shipped ticket ${id} has no title`);
      continue;
    }
    if (!area || !VALID_AREAS.has(area)) {
      problems.push(`${rel}: shipped ticket ${id} has invalid area "${area}"`);
      continue;
    }
    if (!created || !DATE_RE.test(created)) {
      problems.push(`${rel}: shipped ticket ${id} has invalid created "${created}" (expected YYYY-MM-DD)`);
      continue;
    }
    if (created > today) {
      problems.push(`${rel}: shipped ticket ${id} has created "${created}" in the future (today=${today})`);
      continue;
    }

    seenIds.add(id);
    entries.push({ id, title, area: area as ChangelogArea, created });
  }

  // Descending by `created`, then by `id` so same-day ships order deterministically.
  entries.sort((a, b) => (b.created === a.created ? b.id.localeCompare(a.id) : b.created.localeCompare(a.created)));

  return { entries, problems };
}

function renderModule(entries: ChangelogEntry[]): string {
  const header = `// AUTO-GENERATED by scripts/generate-changelog.ts at build time.
// Do not edit by hand - regenerate by running \`npm run build\`.
// Source of truth: docs/backlog/*.md frontmatter (status: shipped).
// Ticket 0032.

export type ChangelogArea =
  | "conversion"
  | "seo"
  | "content"
  | "trust"
  | "demos"
  | "infra"
  | "perf";

export interface ChangelogEntry {
  id: string;
  title: string;
  area: ChangelogArea;
  created: string;
}

export const changelogEntries: readonly ChangelogEntry[] = [
`;
  const body = entries
    .map((e) => {
      // JSON.stringify gives us proper escaping for any quotes / specials
      // in the ticket title.
      return `  { id: ${JSON.stringify(e.id)}, title: ${JSON.stringify(e.title)}, area: ${JSON.stringify(e.area)}, created: ${JSON.stringify(e.created)} },`;
    })
    .join("\n");
  const footer = `\n] as const;\n`;
  return header + body + footer;
}

export function generateChangelog(): { count: number } {
  const { entries, problems } = collectEntries();

  if (problems.length > 0) {
    // Save what we have to a .broken artifact for debugging, matching the
    // sitemap generator's pattern.
    try {
      writeFileSync(BROKEN_PATH, renderModule(entries), "utf-8");
    } catch {
      /* best-effort - don't mask the original failure */
    }
    console.error(`✗ changelog: ${problems.length} validation problem(s); broken file saved to ${relative(ROOT, BROKEN_PATH)}`);
    for (const p of problems) console.error(`  - ${p}`);
    throw new Error(`changelog generator: ${problems.length} validation problem(s)`);
  }

  const out = renderModule(entries);
  writeFileSync(OUT_PATH, out, "utf-8");
  console.log(`✓ Changelog generated with ${entries.length} shipped entries → ${relative(ROOT, OUT_PATH)}`);
  return { count: entries.length };
}

// CLI usage: `npx tsx scripts/generate-changelog.ts` runs the generator
// directly. In the gated build chain it is invoked by
// scripts/generate-sitemap.ts so a single `npm run build` covers both.
const invokedDirectly =
  process.argv[1] && process.argv[1].endsWith("generate-changelog.ts");
if (invokedDirectly) {
  try {
    generateChangelog();
  } catch (err) {
    console.error(err instanceof Error ? err.message : String(err));
    process.exit(1);
  }
}
