/**
 * Reads the user-facing class catalog at api/_classes.json and emits the
 * exact same content as api/_classesData.ts — a plain TS module the
 * Vercel serverless bundler can ingest without import attributes.
 *
 * Run automatically by `npm run dev` (via predev) and `npm run build`
 * (via the build chain), so editing api/_classes.json is the only step
 * needed to add or update a class session.
 */

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const ROOT = join(import.meta.dirname, "..");
const SRC = join(ROOT, "api", "_classes.json");
const OUT = join(ROOT, "api", "_classesData.ts");

function run() {
  const raw = readFileSync(SRC, "utf-8");
  // Validate it parses cleanly so a typo in the JSON fails the build here
  // with a friendly path, rather than later in the TS compile step.
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (e) {
    throw new Error(`api/_classes.json is not valid JSON: ${(e as Error).message}`);
  }
  if (!Array.isArray(parsed)) {
    throw new Error("api/_classes.json must be a JSON array");
  }

  const content = `// AUTO-GENERATED from api/_classes.json by scripts/sync-classes-data.ts.
// Do NOT edit this file directly — edit the JSON and rerun the build.
/* eslint-disable */
export const CLASS_SESSIONS_RAW = ${JSON.stringify(parsed, null, 2)} as const;
`;

  writeFileSync(OUT, content, "utf-8");
  console.log(
    `✓ Classes data synced: ${(parsed as unknown[]).length} session(s) → api/_classesData.ts`,
  );
}

run();
