/**
 * SEO configuration and helper for per-route meta tags.
 * Generated by SEO Pilot — drop this into your React SPA.
 *
 * USAGE:
 * 1. npm install react-helmet-async
 * 2. Wrap your App with <HelmetProvider>
 * 3. Add <SEOHead /> inside each route component
 *
 * Example in App.tsx:
 *   import { HelmetProvider } from "react-helmet-async";
 *   function App() {
 *     return (
 *       <HelmetProvider>
 *         <Routes>...</Routes>
 *       </HelmetProvider>
 *     );
 *   }
 *
 * Example in a page component:
 *   import { SEOHead } from "./seo-config";
 *   function ConstructionPage() {
 *     return (
 *       <>
 *         <SEOHead />
 *         <div>...</div>
 *       </>
 *     );
 *   }
 */
import { Helmet } from "react-helmet-async";
import { useLocation } from "react-router-dom";

interface PageSEO {
  title: string;
  description: string;
  canonical: string;
  ogType?: string;
  jsonLd?: object;
}

const SEO_CONFIG: Record<string, PageSEO> = {
  "/": {
    title: "AI Solutions for Traditional Industries | Practical Business Automation",
    description: "We build AI systems for construction, real estate, and event planning businesses. See live demos personalized to your company.",
    canonical: "https://digitalcraftai.com",
  },
  "/construction": {
    title: "AI Systems for Construction Businesses | DigitalCraft AI",
    description: "We build AI systems for construction, real estate, and event planning businesses. See live demos personalized to your company.",
    canonical: "https://digitalcraftai.com/construction",
  },
  "/construction/demo": {
    title: "Interactive AI Demos for Construction | DigitalCraft AI",
    description: "We build AI systems for construction, real estate, and event planning businesses. See live demos personalized to your company.",
    canonical: "https://digitalcraftai.com/construction/demo",
  },
  "/construction/demo/lead-responder": {
    title: "DigitalCraft AI | AI Automation for Traditional Industries",
    description: "We build AI systems for construction, real estate, and event planning businesses. See live demos personalized to your company.",
    canonical: "https://digitalcraftai.com/construction/demo/lead-responder",
  },
  "/construction/demo/estimate": {
    title: "DigitalCraft AI | AI Automation for Traditional Industries",
    description: "We build AI systems for construction, real estate, and event planning businesses. See live demos personalized to your company.",
    canonical: "https://digitalcraftai.com/construction/demo/estimate",
  },
  "/construction/demo/reviews": {
    title: "DigitalCraft AI | AI Automation for Traditional Industries",
    description: "We build AI systems for construction, real estate, and event planning businesses. See live demos personalized to your company.",
    canonical: "https://digitalcraftai.com/construction/demo/reviews",
  },
  "/construction/demo/property-negotiator": {
    title: "AI Deal Negotiator | DigitalCraft AI",
    description: "We build AI systems for construction, real estate, and event planning businesses. See live demos personalized to your company.",
    canonical: "https://digitalcraftai.com/construction/demo/property-negotiator",
  },
  "/construction/demo/voice-negotiator": {
    title: "AI Voice Negotiator | DigitalCraft AI",
    description: "We build AI systems for construction, real estate, and event planning businesses. See live demos personalized to your company.",
    canonical: "https://digitalcraftai.com/construction/demo/voice-negotiator",
  },
  "/realestate": {
    title: "AI Systems for Real Estate Professionals | DigitalCraft AI",
    description: "We build AI systems for construction, real estate, and event planning businesses. See live demos personalized to your company.",
    canonical: "https://digitalcraftai.com/realestate",
  },
  "/realestate/demo": {
    title: "Interactive AI Demos for Real Estate | DigitalCraft AI",
    description: "We build AI systems for construction, real estate, and event planning businesses. See live demos personalized to your company.",
    canonical: "https://digitalcraftai.com/realestate/demo",
  },
  "/realestate/demo/lead-responder": {
    title: "DigitalCraft AI | AI Automation for Traditional Industries",
    description: "We build AI systems for construction, real estate, and event planning businesses. See live demos personalized to your company.",
    canonical: "https://digitalcraftai.com/realestate/demo/lead-responder",
  },
  "/realestate/demo/property-negotiator": {
    title: "AI Deal Negotiator | DigitalCraft AI",
    description: "We build AI systems for construction, real estate, and event planning businesses. See live demos personalized to your company.",
    canonical: "https://digitalcraftai.com/realestate/demo/property-negotiator",
  },
  "/realestate/demo/voice-negotiator": {
    title: "AI Voice Negotiator | DigitalCraft AI",
    description: "We build AI systems for construction, real estate, and event planning businesses. See live demos personalized to your company.",
    canonical: "https://digitalcraftai.com/realestate/demo/voice-negotiator",
  },
  "/events": {
    title: "AI Systems for Event Planners | DigitalCraft AI",
    description: "We build AI systems for construction, real estate, and event planning businesses. See live demos personalized to your company.",
    canonical: "https://digitalcraftai.com/events",
  },
  "/events/demo": {
    title: "Interactive AI Demos for Event Vendors | DigitalCraft AI",
    description: "We build AI systems for construction, real estate, and event planning businesses. See live demos personalized to your company.",
    canonical: "https://digitalcraftai.com/events/demo",
  },
  "/events/demo/inquiry": {
    title: "DigitalCraft AI | AI Automation for Traditional Industries",
    description: "We build AI systems for construction, real estate, and event planning businesses. See live demos personalized to your company.",
    canonical: "https://digitalcraftai.com/events/demo/inquiry",
  },
  "/events/demo/proposal": {
    title: "DigitalCraft AI | AI Automation for Traditional Industries",
    description: "We build AI systems for construction, real estate, and event planning businesses. See live demos personalized to your company.",
    canonical: "https://digitalcraftai.com/events/demo/proposal",
  },
  "/events/demo/voice-booking": {
    title: "AI Voice Booking Agent | DigitalCraft AI",
    description: "We build AI systems for construction, real estate, and event planning businesses. See live demos personalized to your company.",
    canonical: "https://digitalcraftai.com/events/demo/voice-booking",
  },
  "/month": {
    title: "DigitalCraft AI | AI Automation for Traditional Industries",
    description: "We build AI systems for construction, real estate, and event planning businesses. See live demos personalized to your company.",
    canonical: "https://digitalcraftai.com/month",
  },
  "/sqft": {
    title: "DigitalCraft AI | AI Automation for Traditional Industries",
    description: "We build AI systems for construction, real estate, and event planning businesses. See live demos personalized to your company.",
    canonical: "https://digitalcraftai.com/sqft",
  }
};

const SITE_NAME = "Digitalcraftai";
const SITE_URL = "https://digitalcraftai.com";
const DEFAULT_OG_IMAGE = "https://digitalcraftai.com/og-image.png";

export function SEOHead({ overrides }: { overrides?: Partial<PageSEO> } = {}) {
  const { pathname } = useLocation();
  const config = SEO_CONFIG[pathname] || SEO_CONFIG["/"] || {
    title: SITE_NAME,
    description: "",
    canonical: SITE_URL + pathname,
  };

  const title = overrides?.title || config.title;
  const description = overrides?.description || config.description;
  const canonical = overrides?.canonical || config.canonical;

  return (
    <Helmet>
      <title>{title}</title>
      <meta name="description" content={description} />
      <link rel="canonical" href={canonical} />

      {/* Open Graph */}
      <meta property="og:title" content={title} />
      <meta property="og:description" content={description} />
      <meta property="og:url" content={canonical} />
      <meta property="og:type" content={overrides?.ogType || "website"} />
      <meta property="og:site_name" content={SITE_NAME} />
      <meta property="og:image" content={DEFAULT_OG_IMAGE} />

      {/* Twitter */}
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content={title} />
      <meta name="twitter:description" content={description} />
      <meta name="twitter:image" content={DEFAULT_OG_IMAGE} />
    </Helmet>
  );
}

export { SEO_CONFIG, SITE_NAME, SITE_URL };
