// AUTO-GENERATED by scripts/generate-changelog.ts at build time.
// Do not edit by hand - regenerate by running `npm run build`.
// Source of truth: docs/backlog/*.md frontmatter (status: shipped).
// Ticket 0032.

export type ChangelogArea =
  | "conversion"
  | "seo"
  | "content"
  | "trust"
  | "demos"
  | "infra"
  | "perf";

export interface ChangelogEntry {
  id: string;
  title: string;
  area: ChangelogArea;
  created: string;
}

export const changelogEntries: readonly ChangelogEntry[] = [
  { id: "0035", title: "Comparison page \"Digital Craft vs Podium\" for high-intent SMS and review compares", area: "seo", created: "2026-06-05" },
  { id: "0034", title: "AI-for-electricians long-tail landing page funneling into home-services demos", area: "content", created: "2026-06-05" },
  { id: "0033", title: "Per-demo \"what we store\" disclosure chip linked to /trust", area: "trust", created: "2026-06-03" },
  { id: "0032", title: "Public /changelog page surfacing weekly ship velocity to crawlers and repeat visitors", area: "content", created: "2026-06-03" },
  { id: "0031", title: "\"Try the next demo\" pinned CTA on voice and estimate result screens", area: "demos", created: "2026-06-03" },
  { id: "0030", title: "Emit SoftwareApplication JSON-LD on the /demos hub", area: "seo", created: "2026-06-03" },
  { id: "0029", title: "Shareable branded voice-call summary link", area: "demos", created: "2026-06-01" },
  { id: "0028", title: "Comparison page \"Digital Craft vs ServiceTitan\" for high-intent field-service compares", area: "seo", created: "2026-06-01" },
  { id: "0027", title: "\"More like this\" cross-vertical recommendations under each demo", area: "demos", created: "2026-06-01" },
  { id: "0026", title: "Recently viewed demos recap strip on the /demos hub", area: "demos", created: "2026-05-30" },
  { id: "0025", title: "Emit Organization JSON-LD with sameAs and contactPoint on the homepage", area: "seo", created: "2026-05-30" },
  { id: "0024", title: "AI-for-roofers long-tail landing page funneling into home-services demos", area: "content", created: "2026-05-30" },
  { id: "0023", title: "Footer \"AI providers we use\" trust chip linking to /trust", area: "trust", created: "2026-05-28" },
  { id: "0022", title: "Emit lastmod timestamps in sitemap.xml so Google prioritizes recrawl of fresh routes", area: "seo", created: "2026-05-28" },
  { id: "0021", title: "Comparison page \"Digital Craft vs Jobber\" for high-intent home-services compares", area: "seo", created: "2026-05-28" },
  { id: "0020", title: "AI-for-HVAC long-tail landing page funneling into home-services demos", area: "content", created: "2026-05-28" },
  { id: "0019", title: "Visible breadcrumbs and BreadcrumbList JSON-LD on every demo page", area: "conversion", created: "2026-05-26" },
  { id: "0018", title: "How-the-demos-work transparency page at /trust", area: "trust", created: "2026-05-26" },
  { id: "0017", title: "AI-for-plumbers long-tail landing page funneling into home-services demos", area: "content", created: "2026-05-26" },
  { id: "0016", title: "Emit WebSite + SiteNavigationElement JSON-LD for sitelinks search box", area: "seo", created: "2026-05-26" },
  { id: "0008", title: "Enable strict tsconfig flag (zero-cost ratchet)", area: "infra", created: "2026-05-26" },
  { id: "0015", title: "\"Email me this estimate\" lead capture on the estimate result", area: "conversion", created: "2026-05-25" },
  { id: "0014", title: "Persist and re-offer the visitor's last completed estimate", area: "demos", created: "2026-05-25" },
  { id: "0013", title: "Add DefinedTermSet structured data to the AI glossary", area: "seo", created: "2026-05-25" },
  { id: "0012", title: "Emit FAQPage structured data for the visible pricing FAQ", area: "seo", created: "2026-05-25" },
  { id: "0011", title: "Crawlable /demos index hub with ItemList structured data", area: "seo", created: "2026-05-23" },
  { id: "0010", title: "Resumable demo session with \"Continue your demo\" prompt", area: "demos", created: "2026-05-23" },
  { id: "0009", title: "Shareable branded estimate result link", area: "demos", created: "2026-05-23" },
  { id: "0007", title: "Ratchet tsconfig strictness (zero-cost flags)", area: "infra", created: "2026-05-22" },
  { id: "0006", title: "Footer silently missing on Glossary, Industries, and comparison pages", area: "conversion", created: "2026-05-22" },
  { id: "0005", title: "Add CI type-check gate (tsc --noEmit)", area: "infra", created: "2026-05-22" },
  { id: "0004", title: "Client logo marquee (placeholders)", area: "trust", created: "2026-05-22" },
  { id: "0003", title: "Route-aware dynamic pricing CTA", area: "conversion", created: "2026-05-22" },
  { id: "0002", title: "5-day AI implementation email course opt-in", area: "conversion", created: "2026-05-22" },
  { id: "0001", title: "UTM-personalized hero copy", area: "conversion", created: "2026-05-22" },
] as const;
