// AUTO-GENERATED by scripts/generate-changelog.ts at build time.
// Do not edit by hand - regenerate by running `npm run build`.
// Source of truth: docs/backlog/*.md frontmatter (status: shipped).
// Ticket 0032.

export type ChangelogArea =
  | "conversion"
  | "seo"
  | "content"
  | "trust"
  | "demos"
  | "infra"
  | "perf";

export interface ChangelogEntry {
  id: string;
  title: string;
  area: ChangelogArea;
  created: string;
}

export const changelogEntries: readonly ChangelogEntry[] = [
  { id: "0056", title: "AI-for-pest-control long-tail landing page funneling into home-services demos", area: "content", created: "2026-06-15" },
  { id: "0055", title: "Generate a public /changelog/rss.xml feed of shipped tickets so feed readers and SEO crawlers subscribe to the ship velocity", area: "content", created: "2026-06-15" },
  { id: "0054", title: "Emit Article JSON-LD on every /case-studies/:slug page so each case study indexes as a structured article artifact", area: "seo", created: "2026-06-15" },
  { id: "0053", title: "Comparison page \"Digital Craft vs Angi\" for high-intent home-services lead-marketplace switchers", area: "seo", created: "2026-06-15" },
  { id: "0052", title: "Shareable AI Readiness Quiz result deep-link rendering the tier card from a /quiz?tier= URL", area: "conversion", created: "2026-06-13" },
  { id: "0051", title: "Emit LocalBusiness JSON-LD on /locations/texas so the state-level location page indexes as a local search artifact", area: "seo", created: "2026-06-13" },
  { id: "0050", title: "AI-for-cleaning-services long-tail landing page funneling into home-services demos", area: "content", created: "2026-06-13" },
  { id: "0049", title: "Comparison page \"Digital Craft vs Thumbtack\" for high-intent lead-marketplace switchers", area: "seo", created: "2026-06-13" },
  { id: "0048", title: "Public /compare hub indexing every comparison page with CollectionPage and ItemList JSON-LD", area: "seo", created: "2026-06-11" },
  { id: "0047", title: "AI-for-property-managers long-tail landing page funneling into real-estate demos", area: "content", created: "2026-06-11" },
  { id: "0046", title: "Shareable AI ROI calculator producing a branded annual savings result link", area: "conversion", created: "2026-06-11" },
  { id: "0045", title: "Personalized /my visitor dashboard surfacing saved estimates, recent demos, and quiz persona", area: "demos", created: "2026-06-11" },
  { id: "0044", title: "Emit AboutPage + BreadcrumbList JSON-LD on /trust so the data-handling disclosure indexes as a canonical artifact", area: "seo", created: "2026-06-09" },
  { id: "0043", title: "Emit ItemList JSON-LD on /changelog so search engines can index individual ship entries", area: "seo", created: "2026-06-09" },
  { id: "0042", title: "Comparison page \"Digital Craft vs Buildertrend\" for high-intent construction-software switchers", area: "seo", created: "2026-06-09" },
  { id: "0041", title: "AI-for-landscapers long-tail landing page funneling into home-services demos", area: "content", created: "2026-06-09" },
  { id: "0040", title: "\"What's new since you visited\" delta strip on the /demos hub for week-2-and-beyond returners", area: "demos", created: "2026-06-07" },
  { id: "0039", title: "Emit Quiz JSON-LD on the AI Readiness Quiz for question-rich-result eligibility", area: "seo", created: "2026-06-07" },
  { id: "0038", title: "Comparison page \"Digital Craft vs Housecall Pro\" for high-intent field-service buyers", area: "seo", created: "2026-06-07" },
  { id: "0037", title: "AI-for-painters long-tail landing page funneling into home-services demos", area: "content", created: "2026-06-07" },
  { id: "0036", title: "Public /uptime page surfacing demo and serverless health for regulated-vertical buyers", area: "trust", created: "2026-06-05" },
  { id: "0035", title: "Comparison page \"Digital Craft vs Podium\" for high-intent SMS and review compares", area: "seo", created: "2026-06-05" },
  { id: "0034", title: "AI-for-electricians long-tail landing page funneling into home-services demos", area: "content", created: "2026-06-05" },
  { id: "0033", title: "Per-demo \"what we store\" disclosure chip linked to /trust", area: "trust", created: "2026-06-03" },
  { id: "0032", title: "Public /changelog page surfacing weekly ship velocity to crawlers and repeat visitors", area: "content", created: "2026-06-03" },
  { id: "0031", title: "\"Try the next demo\" pinned CTA on voice and estimate result screens", area: "demos", created: "2026-06-03" },
  { id: "0030", title: "Emit SoftwareApplication JSON-LD on the /demos hub", area: "seo", created: "2026-06-03" },
  { id: "0029", title: "Shareable branded voice-call summary link", area: "demos", created: "2026-06-01" },
  { id: "0028", title: "Comparison page \"Digital Craft vs ServiceTitan\" for high-intent field-service compares", area: "seo", created: "2026-06-01" },
  { id: "0027", title: "\"More like this\" cross-vertical recommendations under each demo", area: "demos", created: "2026-06-01" },
  { id: "0026", title: "Recently viewed demos recap strip on the /demos hub", area: "demos", created: "2026-05-30" },
  { id: "0025", title: "Emit Organization JSON-LD with sameAs and contactPoint on the homepage", area: "seo", created: "2026-05-30" },
  { id: "0024", title: "AI-for-roofers long-tail landing page funneling into home-services demos", area: "content", created: "2026-05-30" },
  { id: "0023", title: "Footer \"AI providers we use\" trust chip linking to /trust", area: "trust", created: "2026-05-28" },
  { id: "0022", title: "Emit lastmod timestamps in sitemap.xml so Google prioritizes recrawl of fresh routes", area: "seo", created: "2026-05-28" },
  { id: "0021", title: "Comparison page \"Digital Craft vs Jobber\" for high-intent home-services compares", area: "seo", created: "2026-05-28" },
  { id: "0020", title: "AI-for-HVAC long-tail landing page funneling into home-services demos", area: "content", created: "2026-05-28" },
  { id: "0019", title: "Visible breadcrumbs and BreadcrumbList JSON-LD on every demo page", area: "conversion", created: "2026-05-26" },
  { id: "0018", title: "How-the-demos-work transparency page at /trust", area: "trust", created: "2026-05-26" },
  { id: "0017", title: "AI-for-plumbers long-tail landing page funneling into home-services demos", area: "content", created: "2026-05-26" },
  { id: "0016", title: "Emit WebSite + SiteNavigationElement JSON-LD for sitelinks search box", area: "seo", created: "2026-05-26" },
  { id: "0008", title: "Enable strict tsconfig flag (zero-cost ratchet)", area: "infra", created: "2026-05-26" },
  { id: "0015", title: "\"Email me this estimate\" lead capture on the estimate result", area: "conversion", created: "2026-05-25" },
  { id: "0014", title: "Persist and re-offer the visitor's last completed estimate", area: "demos", created: "2026-05-25" },
  { id: "0013", title: "Add DefinedTermSet structured data to the AI glossary", area: "seo", created: "2026-05-25" },
  { id: "0012", title: "Emit FAQPage structured data for the visible pricing FAQ", area: "seo", created: "2026-05-25" },
  { id: "0011", title: "Crawlable /demos index hub with ItemList structured data", area: "seo", created: "2026-05-23" },
  { id: "0010", title: "Resumable demo session with \"Continue your demo\" prompt", area: "demos", created: "2026-05-23" },
  { id: "0009", title: "Shareable branded estimate result link", area: "demos", created: "2026-05-23" },
  { id: "0007", title: "Ratchet tsconfig strictness (zero-cost flags)", area: "infra", created: "2026-05-22" },
  { id: "0006", title: "Footer silently missing on Glossary, Industries, and comparison pages", area: "conversion", created: "2026-05-22" },
  { id: "0005", title: "Add CI type-check gate (tsc --noEmit)", area: "infra", created: "2026-05-22" },
  { id: "0004", title: "Client logo marquee (placeholders)", area: "trust", created: "2026-05-22" },
  { id: "0003", title: "Route-aware dynamic pricing CTA", area: "conversion", created: "2026-05-22" },
  { id: "0002", title: "5-day AI implementation email course opt-in", area: "conversion", created: "2026-05-22" },
  { id: "0001", title: "UTM-personalized hero copy", area: "conversion", created: "2026-05-22" },
] as const;
