// AUTO-GENERATED by scripts/generate-roadmap.ts at build time.
// Do not edit by hand - regenerate by running `npm run build`.
// Source of truth: docs/backlog/*.md frontmatter (status: groomed or in-progress).
// Ticket 0108.

export type RoadmapArea = "conversion" | "seo" | "content" | "trust" | "demos";
export type RoadmapPriority = "P0" | "P1" | "P2" | "P3";
export type RoadmapStatus = "groomed" | "in-progress";

export interface RoadmapEntry {
  id: string;
  title: string;
  priority: RoadmapPriority;
  area: RoadmapArea;
  status: RoadmapStatus;
  created: string;
  intendedShipWeek: string;
}

export const ROADMAP_GENERATED_AT: string = "2026-10-02";

export const ROADMAP_CADENCE_NOTE: string = "The ship loop runs one ticket per hour and typically lands 1-5 tickets per week based on backlog depth, heal retries, and reviewer blocks. Dates below are a planning signal, not a commitment: the autonomous ship loop reorders groomed tickets as the queue evolves, so an intended ship week can slip or accelerate.";

export const ROADMAP_ENTRIES: readonly RoadmapEntry[] = [
  { id: "0109", title: "Public /agent-prompts transparency page listing the committed system prompt for every autonomous agent as a defensible moat artifact", priority: "P2", area: "trust", status: "in-progress", created: "2026-10-02", intendedShipWeek: "2026-W41" },
] as const;
